### ISSUE TITLE
Improve mobile experience

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#706]
- [x] support inline toolbar
- [x] remove taps highlighting
- [x] fix autocomplete overlaying of Toolbox
- [x] improve UX details

**Comment by ohsik** [comment]
Current behavior on mobile.
![IMG_7404](https://user-images.githubusercontent.com/4256774/56069024-ee0d2700-5d35-11e9-8f9a-6a6451374762.PNG)
![IMG_7405](https://user-images.githubusercontent.com/4256774/56069025-eea5bd80-5d35-11e9-8405-a41e78320f4d.PNG)

Ideal behavior on mobile if possible.
![IMG_7406](https://user-images.githubusercontent.com/4256774/56069074-31679580-5d36-11e9-8b0f-19b00c7dbf05.jpg)

**Comment by tkaravou** [comment]
The editor doesn't work at all on iPad on both Safari and Chrome. You are able to type and use the native commands that IOS has such as bold and underline. However, you can't use any other inline tools. There is no link button for example.

**Comment by gohabereg** [comment]
Resolved by #826
