### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by neSpecc** [codex-team/editor.js#837]
Add the ability to enable read-only mode. We need to support initialization in read-only mode and toggling read-only mode on the fly.

**For each plugin in [list](http://github.com/editor-js):**

- [ ] Improve Tools design that can be represented as WYSIWYG

- [ ] Accept `readOnly` boolean flag in tools constructor and save it to the class's property.

- [ ] Separate event bindings and `contenteditable` attributes activating to the `toggleReadonly(status)` method. Call this method with `true` status on the render in read-only mode. Also, this method can be called with `true/false` statuses by editorjs core — it should bind/unbind events corresponded by status.

**Working with editor.js core:**

- [ ] Add `readOnly` option to the Editor Config

- [ ] Make `readonly.ts` module that will store `readOnlyEnabled` property and have `toggleReadonly(status)` public method.

- [ ] `toggleReadonly(status)` method of `readonly.ts` module will call `toggleReadonly(status)` methods of each editor module implemented this method.

- [ ] Implement `toggleReadonly(status)` method in modules that requires some readonly toggling logic: `UI`, `Toolbar`, `InlineToolbar`, `Paste`, `Saver`, `Shortcuts` (for disabling `cmd+x`), `BlockSettings`, `BlockEvents`, `BlockManager`, `DragNdrop`, `ModificationObserver`, `API`. This method will do two things: bind/unbind events and make/remove dom elements.

- [ ] If some module makes own ui and bind events in `prepare` method (for example, `UI`, `Toolbar`): move events binding and ui making in `toggleReadonly()` method of this module. Then call `toggleReadonly()` in prepare.

- [ ] Pass `readOnly` option to Tools constructor on render

- [ ] If some of Tools does not provide read-only functionality (can be detected by `toggleReadonly () implemented or not`), throw an error on trying to enable read-only mode. 

- [ ] add `toggleReadonly()` method to the public API. This method will call `toggleReadonly(status)` method of `readonly.ts` module internally.

**Comment by startupgurukul** [comment]
Hi folks, don't mean to be pushy, Any chances of this being looked at earlier. Read-only is a very nice feature to have

**Comment by neSpecc** [comment]
@startupgurukul you can boost development by donation to maintainers https://opencollective.com/editorjs

**Comment by themzed** [comment]
Hi, I'm interested for maintaining this project. Could we talk about this?

**Comment by neSpecc** [comment]
@themzed cool, join Telegram chat for core contributors: https://t.me/editorjsdev 

Then, we will discuss the first steps.

**Comment by themzed** [comment]
I joined and my Telegram id is: https://t.me/themzed

**Comment by startupgurukul** [comment]
@neSpecc we are about to launch a product using editor and soon we will be in a position to donate until then we will be happy to contribute in form of code, in the mean time I am sure you must have seen this https://github.com/sponsors

**Comment by andersan** [comment]
Hello,

Any news on this feature?

Considering using this for a project, but I'm hesitant due to the additional work involved with finding or writing a JSON parser. I'd be fine with the Read Only mode only supporting the Core parts of Editor.js.

**Comment by neSpecc** [comment]
I've updated the description of the issue with more details. We are looking for contributors who can implement some of the subtasks with our help.

**Comment by marcovc** [comment]
Hi, it seems one cannot query the readOnly.isEnabled property. Is this how it is supposed to be? It is hard to know when to call toogleReadOnly if we don't know the current readOnly value of the component. And maintaining an external bool with this seems odd.
